DROP TABLE IF EXISTS User;
CREATE TABLE User (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    password TEXT NOT NULL
);

DROP TABLE IF EXISTS List;
CREATE TABLE List (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES User(id)
);

DROP TABLE IF EXISTS Task;
CREATE TABLE Task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    list_id INTEGER,
    detail TEXT,
    name TEXT NOT NULL,
    FOREIGN KEY(list_id) REFERENCES List(id)
);

